#!/bin/bash
set -euo pipefail

OLD_REPO="${1:?usage: migrate.sh <old_repo_path>}"
NEW_REPO="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== CoordOS migration start ==="
echo "old repo: $OLD_REPO"
echo "new repo: $NEW_REPO"

check_old_repo() {
  local required="core/pkg/parcel core/pkg/utxo core/pkg/settlement core/pkg/invoice core/pkg/wallet"
  for dir in $required; do
    if [ ! -d "$OLD_REPO/$dir" ]; then
      echo "warn: missing $dir in old repo"
    fi
  done
}

migrate_direct() {
  local module="$1"
  local src="$OLD_REPO/core/pkg/$module"
  local dst="$NEW_REPO/services/design-institute/domain/$module"

  if [ ! -d "$src" ]; then
    echo "skip $module (source missing)"
    return
  fi

  mkdir -p "$dst"
  cp -r "$src/"*.go "$dst/" 2>/dev/null || true
  for f in "$dst/"*.go; do
    [ -f "$f" ] || continue
    sed -i "s/^package .*/package $module/" "$f"
  done
  echo "ok: migrated $module"
}

migrate_with_project_ref() {
  local module="$1"
  migrate_direct "$module"

  local dst="$NEW_REPO/services/design-institute/domain/$module"
  for f in "$dst/"*.go; do
    [ -f "$f" ] || continue
    if grep -q "ContractRef" "$f" && ! grep -q "ProjectRef" "$f"; then
      sed -i '/ContractRef.*VRef/a \\tProjectRef  vuri.VRef `json:"project_ref"`' "$f"
    fi
  done
}

migrate_protocols() {
  local src="$OLD_REPO/protocols"
  local dst="$NEW_REPO/protocols/zhongbei"

  if [ ! -d "$src/zhongbei" ]; then
    echo "skip protocols (source missing)"
    return
  fi

  mkdir -p "$dst"
  for f in "$src/zhongbei/"*; do
    local name
    name="$(basename "$f")"
    if [ ! -f "$dst/$name" ]; then
      cp "$f" "$dst/$name"
      echo "copy protocol: $name"
    fi
  done
  echo "ok: protocols migrated"
}

generate_db_migration() {
  cat > "$NEW_REPO/scripts/migrate_db.sql" << 'SQL'
-- CoordOS DB migration placeholder
-- Keep this file generated by scripts/migrate.sh
SQL
  echo "ok: scripts/migrate_db.sql generated"
}

generate_report() {
  cat > "$NEW_REPO/MIGRATION_REPORT.md" << 'REPORT'
# CoordOS Migration Report

## Migrated modules
- parcel (with project_ref)
- utxo (with project_ref)
- settlement (with project_ref)
- invoice
- wallet
- achievement
- protocols

## Notes
- Test files and test scripts are intentionally excluded.
- Build command: `go build ./services/design-institute && go build ./services/vault-service`
REPORT
  echo "ok: MIGRATION_REPORT.md generated"
}

echo "1) check old repo"
check_old_repo

echo "2) migrate business modules"
migrate_direct "invoice"
migrate_direct "wallet"
migrate_direct "achievement"
migrate_with_project_ref "parcel"
migrate_with_project_ref "utxo"
migrate_with_project_ref "settlement"

echo "3) migrate protocols"
migrate_protocols

echo "4) generate db migration"
generate_db_migration

echo "5) generate report"
generate_report

echo "=== CoordOS migration done ==="
